# ProfitBot Configuration
# Trading simulation settings

# Initial portfolio settings
initial_balance: 1000.0  # Starting USDT balance

# Strategy selection (only optimized strategy available)
strategy_mode: "optimized"  # Optimized momentum scalp strategy

# Coins to track and trade (only Alpaca-supported coins)
coins:
  BTC:
    initial_price: 30000.0
    volatility: 0.08  # 2% volatility factor
  ETH:
    initial_price: 2000.0
    volatility: 0.1  # 2.5% volatility factor
  SOL:
    initial_price: 100.0
    volatility: 0.12  # 3% volatility factor
  XRP:
    initial_price: 0.5
    volatility: 0.15  # 3.5% volatility factor

# Enhanced Trading Strategy Settings
strategy:
  # Legacy parameters (kept for compatibility)
  movement_threshold: 0.03  # Base threshold (now adaptive per coin)
  trade_amount_percentage: 0.1  # Base trade percentage for sells
  min_trade_amount: 10.0  # Minimum trade amount in USDT
  
  # 🧠 ADAPTIVE THRESHOLDS
  adaptive_k_factor: 1.5  # Multiplier for volatility-based thresholds
  # Formula: threshold = coin_volatility * k_factor
  
  # 🔄 SMART BASELINE UPDATES  
  baseline_update_weight: 0.3  # Weight for baseline updates (0.3 = 30% new price, 70% old)
  
  # 📈 MOMENTUM FILTER
  momentum_threshold: 0.0  # Only buy if momentum >= this value (0 = no falling knife)
  
  # 📊 TIERED DCA SYSTEM
  dca_multipliers: [0.10, 0.15, 0.20]  # Trade sizes: 10%, 15%, 20% of balance
  # First buy: 10%, Second DCA: 15%, Third DCA: 20%
  
  # ⏰ TIMED SELL FALLBACK
  timed_sell_threshold: 0.015  # 1.5% - sell if held too long and up this much
  timed_sell_percentage: 0.05  # 5% - sell this portion during timed sells
  max_hold_ticks: 300  # 300 seconds (5 minutes) max hold time
  
  # 💰 PROFIT REBALANCING
  rebalance_profit_threshold: 0.01  # Rebalance when portfolio grows 1%
  rebalance_percentage: 0.10  # Sell 10% of all holdings during rebalance
  
  # 🔬 MULTI-SIGNAL ANALYSIS
  min_signal_strength: 0.2  # Minimum signal strength to trigger trades (0.0-1.0)
  min_volume_threshold: 1000000  # Minimum $1M daily volume for trades
  rsi_overbought: 70  # RSI overbought level
  rsi_oversold: 30   # RSI oversold level
  
  # 😱 FEAR & GREED ADJUSTMENTS
  fear_greed_multipliers:
    extreme_fear: 0.7    # More aggressive (lower thresholds) during extreme fear
    fear: 0.85           # Slightly more aggressive during fear
    neutral: 1.0         # Normal thresholds when neutral
    greed: 1.15          # More conservative (higher thresholds) during greed
    extreme_greed: 1.4   # Much more conservative during extreme greed

# API settings (CoinGecko removed - using Alpaca for data)
api:
  use_real_prices: true  # Set to false to use simulation mode
  price_update_interval: 15.0  # Seconds between price updates

# Alpaca Markets paper trading settings
# Set these as environment variables: ALPACA_API_KEY, ALPACA_SECRET_KEY
alpaca:
  api_key: ""  # Set via ALPACA_API_KEY environment variable
  secret_key: ""  # Set via ALPACA_SECRET_KEY environment variable
  base_url: "https://paper-api.alpaca.markets"  # Paper trading URL
  use_paper_trading: true  # Set to false for live trading (NOT RECOMMENDED without testing)

# Telegram notifications
# Set bot_token as environment variable: TELEGRAM_BOT_TOKEN
telegram:
  bot_token: ""  # Set via TELEGRAM_BOT_TOKEN environment variable
  chat_id: ""  # Set via TELEGRAM_CHAT_ID environment variable (or leave empty for auto-detect)
  enable_notifications: true
  hourly_updates: true
  trade_alerts: true


# Simulation settings (used when use_real_prices is false)
simulation:
  tick_interval: 1.0  # Seconds between price updates
  price_update_factor: 0.005  # Max price change per tick (0.5%)
  
# Logging settings
logging:
  log_file: "data/trading.log"
  trade_history_file: "data/trade_history.csv"
  log_level: "INFO"